### ISSUE TITLE
Docker compose - Internal server error

### ISSUE THREAD

**Issue by stra1ghtarrow90** [cmu-sei/GHOSTS#154]
Hi,

I've tried building this with docker-compose on two separate Ubuntu servers and I'm getting internal server error 500 when I try reach the API - http://10.20.40.10:52388/api/clientid

Am I missing something here or is something broken.

**Comment by sei-dupdyke** [comment]
Hi, hmm, that should work. Let's troubleshoot please. Would you please run:

1. `docker ps --all` — are all three containers up?
2. if yes, run `docker logs ghosts-api` are there connection errors to the database or something similar?

**Comment by sei-dupdyke** [comment]
Standby, I'm looking at this (this is a new one).

**Comment by sei-dupdyke** [comment]
Hmm, no idea why this is not working. 

Here are two strategies in the meantime:

1. modify the config inside the container:

```
docker cp ghosts:/app/appsettings.json .
nano appsettings.json

// now change the connection string from "ghosts-postgres" to "localhost" leave everything else alone, save, and exit

docker cp appsettings ghosts:/app/appsettings.json
docker restart ghosts
```

2. add a hosts entry for ghosts-postgres. In your hosts file add the entry:

ghosts-postgres 127.0.0.1

I'm still looking on this side as to what the root issue is, but I have not seen this before.

**Comment by stra1ghtarrow90** [comment]
Hi, thanks for getting back to me. I've just tried to implement these steps on a new container but now grafana isn't accepting the default admin:admin username/password. Has it changed?

**Comment by sei-dupdyke** [comment]
No, but sometimes you have to refresh the datasource. Go to datasources, and go into the ghosts data source and just save it (don't change anything) and it should work again. Sorry for the inconveniences.

**Comment by sei-dupdyke** [comment]
This morning, I...

1. Built a brand-new ubuntu 20.04 VM
2. Installed docker via apt-get, following the steps [from docker docs](https://docs.docker.com/engine/install/ubuntu/) - docker version 20.10.21
3. Installed docker-compose [following the details here](https://linuxize.com/post/how-to-install-and-use-docker-compose-on-ubuntu-20-04/) - docker-compose version 1.25.5
4. Created a new folder in /tmp and created a new ghosts directory and cd'ed into that directory - so /tmp/ghosts - so that everything was a fresh copy down
5. Copied the current docker-compose into a file via `curl -o docker-compose.yml https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Api/docker-compose.yml`
6. Ran `docker-compose up -d`
7. Went to the browser and visited http://localhost:5000

I verified everything works as expected. I did not get a 500 error. So the questions might be:

1. Did you use some other host OS?
2. Some other install of docker, or some other version? (I see there are options to install via snap, and others. I used apt-get)
3. Some other version of docker-compose? (I see there is a version of "docker compose" out now, but I had nothing but issues with it on ubuntu - seems to work fine on MacOs though)
4. Some other docker-compose file?

**Comment by Mythmaster4** [comment]
> Hi have the same Issue,
> 
> I installed Docker using the guide @sei-dupdyke suggested I also used default dockerfile I tried both Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1 and on Ubuntu 22.04.1 Docker version 20.10.21, build baeda1f I am able to connect to http://myip:5000 and get the swagger web-interface, however when trying an api-request this happens. ![Screenshot_20221214_151902](https://user-images.githubusercontent.com/58037230/207619962-e4e023bd-9bb4-4a9c-9ca6-b275ea1bee88.png)

[errorlog.txt](https://github.com/cmu-sei/GHOSTS/files/10228735/errorlog.txt)

**Comment by sei-dupdyke** [comment]
Hmm, this is a different error — line 31 tells us:

at Ghosts.Api.Controllers.ClientIdController.Index(CancellationToken ct) in /app/Ghosts.Api/Controllers/ClientIdController.cs:line 45

Only clients (which configure certain headers used by ghosts) can hit this endpoint (and all of the other client ones). Did you execute it via swagger? If so, that's going to throw an exception every time (by design).

**Comment by Mythmaster4** [comment]
> 
Thank you for your response.
yes this was executed using swagger, Sorry if this is a different issue, then I will look further

This is the log from one of the clients though.
[errorlogclient.txt](https://github.com/cmu-sei/GHOSTS/files/10228905/errorlogclient.txt)

**Comment by Mythmaster4** [comment]
> > 
> 
> Thank you for your response. yes this was executed using swagger, Sorry if this is a different issue, then I will look further
> 
> This is the log from one of the clients though. [errorlogclient.txt](https://github.com/cmu-sei/GHOSTS/files/10228905/errorlogclient.txt)

I figured out the problem (at least for me) port in default docker-compose changed from 52388 to 5000 [https://github.com/cmu-sei/GHOSTS/commit/d9629614acf5f72bd57cdcd51ee945a8f3d631f5](url) changing this back solves the issue for me.

**Comment by sei-dupdyke** [comment]
Good to hear, sorry for the confusion. Didn't someone say that picking names, ports, etc. is the hardest thing in CS? ;)
