### ISSUE TITLE
Word and PowerPoint don't close/exit after file creation/modification

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#180]
Not sure if it's expected behavior, but when the agents open Word/PowerPoint and creates/updates a file, it doesn't close/stop/kill the process. Excel doesn't have this behavior. Using v7.

**Comment by sei-dupdyke** [comment]
This took me a while to find. It was actually a problem with Excel in that it was not respecting the delayAfter value. What happens is Excel, PowerPoint, or Word fire, write a file within their window, and then spend the rest of the window sitting there. Excel was exiting first without checking this value. If you don't want it to hang around, then set the delayAfter value to 0.

This is fixed in 7.0.35.0, which is out there now.

**Comment by sei-dupdyke** [comment]
I should note that most of the default timelines floating around this project use some non-zero delayAfter value.

**Comment by Cyb3r-Monk** [comment]
So, I should use delayBefore to create/edit Office files every X  hours/minutes?

**Comment by sei-dupdyke** [comment]
Up to you - in that case, it will open and wait to create a file for whatever value you enter.
