### ISSUE TITLE
No attachment was downloaded with outlookv2 handler

### ISSUE THREAD

**Issue by sirbowen78** [cmu-sei/GHOSTS#206]
![Screenshot 2023-04-05 112238](https://user-images.githubusercontent.com/53977230/229973879-53b34773-1c45-493d-af6e-969a2fda5781.png)

I have an email with an attachment, my json config as follows:
```
 '{
  "machineId": "84b063ce-4a87-4bfb-a1ec-c9b981d3bff5",
  "type": "Timeline",
  "Update": {
    "TimeLineHandlers": [
      {
        "HandlerType": "Outlookv2",
        "UtcTimeOn": "00:00:00",
        "UtcTimeOff": "24.00:00:00",
        "Loop": true,
        "HandlerArgs": {
          "delay-jitter": 50,
          "delete-probability": 30,
          "create-probability": 0,
          "read-probability": 100,
          "reply-probability": 0,
          "click-probability": 0,
          "attachment-probability": 0,
          "save-attachment-probability": 100,
          "download-probability": 100,
          "min-attachments": 5,
          "max-attachments": 5,
          "input-directory": "C:\\ghosts_data\\uploads",
          "output-directory": "C:\\ghosts_data\\downloads"
        },
        "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "read",
          "CommandArgs": [],
            "DelayAfter": 900000,
            "DelayBefore": 0
          }
        ]
      }
    ]
  }
}
'
```
I am expecting ghosts agent to download or save attachment to C:\ghosts_data\downloads\ always, however only the C:\ghosts_datas\downloads directory is created but there is nothing in the directory, have I misunderstood the downloading of attachment part or is my probability is wrong or is my json config is wrong?

Thank you.

**Comment by rbreesems** [comment]
Sorry,  I have not been looking at these issues.  Your read+delete+create+reply probabilities should <= 100.  If this is not true, then they are set to defaults of read=25, delete=10,create=40,reply=25.

Just because  an email arrives in the inbox does not mean it is 'read'.   The read logic will pull a random email from the inbox and display it in a window.  This also should cause the attachments to be downloaded based on save-attachment-probability which you have as '100'.

For a test, try setting read=100, delete=0,create=0, reply=0 and manually send an email with attachments.
