### ISSUE TITLE
API largely undocumented: how do I use timeline update

### ISSUE THREAD

**Issue by swilliams70** [cmu-sei/GHOSTS#22]
Hi, let me start with the sugar: this is a great project that we have used in our cyber range to great effect. 

I know it can do more than we have made it do, but are a little hampered by the state of the API and the lack of any sort of actual interface by which to invoke the methods. Now, I know that I can go to "localhost:5000/swagger" and get the dynamic API documentation and some basic interface to the API. The issue is that it's not completely obvious to me what "right" looks like when I want to do something - most specifically, update a timeline (although I'm interested in what else useful I can do via the API). I know that I can work it out in time...but I was really hoping to save on the PITA factor and put more energy into making my ghosts behaving in the dynamic way I know they can.

Any way you can give an example of what a "proper" timeline update looks like?

**Comment by sei-dupdyke** [comment]
Hi thanks for the sugar, we do love to hear that these tools are getting use out in the wild!

Also, if you want to get into specifics, you can email me at the address listed in this file https://github.com/cmu-sei/GHOSTS/blob/master/Ghosts.Api/Ghosts.Api.csproj

I hate to sound like a consultant, but I guess it depends on what you want to do, and what your workflow is. I can give you a couple of examples of what we do at the mothership:

If we have machines that are going to run a pretty well randomized timeline through an exercise, then we deploy them and only update them as needed. So in this case, we work out a "good" timeline that we're happy with on a single box, and clone it into however many we need for the exercise. This is probably most used for blue enclaves you're going to defend, because once you have that initial one, they don't change much. 

If we have a few machines that we want to perform specific activity, then we deploy them as above, and use the api to change their timeline when we need them to do that specific thing. At api/timeline, you post new timelines for a single machine or groups, and this completely replaces the original timeline for that machine. So, you have the power to do something like:

Run timeline A
Run timeline B (via API post) - so now machine is doing something specific, maybe downloading malware or making some other "user mistake"
Run timeline A (via API post) - now machine is back to normal

There are other ways to update timelines as well. In larger enclaves we often do this via Ansible or something similar. If you're interested in that, I can provide more detail.

I don't currently have a "system" for managing timelines, even for posting A and B through the api in the example above. What we typically do is have a folder structure for them, and swap them around as needed. I could probably build something in python pretty quickly to do that, I'd just have to think about what makes sense for how everyone is using the api...

If you have more questions, please ask!

**Comment by swilliams70** [comment]
You pretty well describe the use case I'm shooting for:

- Run timeline A
- Run timeline B (via API post) - so now machine is doing something specific, maybe downloading malware or making some other "user mistake"
- Run timeline A (via API post) - now machine is back to normal

(By the way the first use case you describe is pretty much what we did for our last exercise - deploy a known "good" timeline to user endpoints. It worked handsomely - I'm just looking for ways to make the sim more dynamic in terms of realistic user behavior.)

The part I'm, struggling with is what the post looks like...I do well with examples. Is the POST with the entire timeline.json as a string? Are you shaping the POST with something like Requests library? If not that, what sort of framework do you use/recommend? Does the Timeline update completely replace the timeline on the client machine, or append it somehow?

**Comment by sei-dupdyke** [comment]
Stand by for example...

**Comment by sei-dupdyke** [comment]
Here is a quick and dirty, sub your machine id, and server url:

datenow should be in this format: 2019-11-14T21:03:55.521Z

```
import requests

url = "http://<your server url or ip>/timeline"

payload = "{\n  \"machineId\": \"<your machine id you want to update>\",\n  \"type\": \"Timeline\",\n  \"activeUtc\": \"<date now>\",\n  \"status\": \"Active\",\n  \"update\": $t\n}"

data = ""
with open("timeline.json") as f:
    data = f.read()

payload = payload.replace("$t", data)


headers = {
    'Content-Type': "application/json",
    'Accept': "*/*",
    'Cache-Control': "no-cache",
    'Host': "<your server url or ip>",
    'Accept-Encoding': "gzip, deflate",
    'Connection': "keep-alive",
    'cache-control': "no-cache"
}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.status_code)
# should get a 204 no-content
```

**Comment by pcGithub2** [comment]
> Any way you can give an example of what a "proper" timeline update looks like?

er \\nec-file\schedule
explorer \\nec-file\reports

**Comment by sei-dupdyke** [comment]
Any of the timelines here would work: 

https://github.com/cmu-sei/GHOSTS/tree/master/Ghosts.Client/Sample%20Timelines

Or you can mix and match to suit your own.  

These \\nec-file\schedule and \\nec-file\reports entries are just sample file server paths. These create smb browse traffic to the shared file server from the client workstations.

**Comment by adavisec** [comment]
Greetings, I am really enjoying this project! Thanks for sharing it.

I also have a question regarding the timeline updates via the API.

I am able to send updated timelines to the api via swagger and remotely via python. I receive a 204 response, but the timeline shows up on the client and in the database with all of the commandArgs as {ValueKind:3}. I've poked around for a while trying to troubleshoot and understand how this is happening, but I have hit a wall and figured I should ask if I am overlooking something.

Also, in my attempts to send the remote updates I had to work through a lot of 500 response codes due to what I suspect were syntax errors in my json. Is there a log location or a debug setting that I could use to more efficiently troubleshoot these errors? I was looking around in the containers but didn't find much.
 
I am running the latest pre-built client executable and docker containers.

**Comment by swilliams70** [comment]
Check out the "Popular Answer" here:
https://entityframeworkcore.com/knowledge-base/60990373/how-to-bind-dictionary-string-object--in-asp-net-core-for-entity-framework-

Seems to describe the issue you're having and points in a direction that might answer it....

Also, have a screenshot of the issue? I'm having a hard time picturing what you're describing, where you're seeing it and how.

Lastly, obviously you should believe any answer Dustin gives you over anything I say! :)

**Comment by swilliams70** [comment]
....oh, and check this out: 

https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.valuekind?view=netcore-3.1#System_Text_Json_JsonElement_ValueKind

Type 3 would indicate it's a string value.

**Comment by sei-dupdyke** [comment]
Hi, thanks for reaching out - do you have a copy of the json that you posted and caused the error?

Off the top of my head I suspect an enum value or something like that, but I'm not sure. I'll do some digging around this morning...

**Comment by adavisec** [comment]
Thanks for the replies.
Here is a short version of what I am posting to the API:
```
{
  "machineId": "20ba0a08-01c9-4358-a99f-bac850281741",
  "type": 0,
  "activeUtc": "2020-06-16T18:00:00.000Z",
  "status": 0,
  "update": {
    "status": 0,
    "timeLineHandlers": [
      {
        "handlerType": 0,
        "initial": "about:blank",
        "utcTimeOn": {},
        "utcTimeOff": {},
        "loop": true,
        "timeLineEvents": [
          {
            "command": "random",
            "commandArgs": [
                        "http://www.ceoexpress.com",
                        "http://wikipedia.org",
                        "http://ebay.com",
                        "http://craigslist.org",
                        "http://reddit.com",
                        "http://instagram.com",
                        "http://imdb.com",
                        "http://huffingtonpost.com",
                        "http://nytimes.com",
                        "http://msn.com",
                        "http://buzzfeed.com"
            ],
            "delayAfter": 90000,
            "delayBefore": 0
          }
        ]
      },
      {
        "handlerType": 8,
        "initial": "",
        "utcTimeOn": {},
        "utcTimeOff": {},
        "loop": true,
        "timeLineEvents": [
	  {
            "command": "create",
            "commandArgs": ["%homedrive%%homepath%\\Documents"],
            "delayAfter": 900000,
            "delayBefore": 0
          }
        ]
      }
    ]
  }
}
```
<Response [204]>


This is what shows up on the client machine in config\timeline.json

```
{
  "Status": "Run",
  "TimeLineHandlers": [
    {
      "HandlerType": "BrowserIE",
      "Initial": "about:blank",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "00:00:00",
      "HandlerArgs": {},
      "Loop": true,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "random",
          "CommandArgs": [
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            },
            {
              "ValueKind": 3
            }
          ],
          "DelayAfter": 90000,
          "DelayBefore": 0
        }
      ]
    },
    {
      "HandlerType": "PowerPoint",
      "Initial": "",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "00:00:00",
      "HandlerArgs": {},
      "Loop": true,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "create",
          "CommandArgs": [
            {
              "ValueKind": 3
            }
          ],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
      ]
    }
  ]
}
```

**Comment by swilliams70** [comment]
Why are you using enum values for the handler types? It seems like you're forcing the parser to parse the enums into strings, then when it hits the string it parses those into enum values. Just use all string values maybe...

This:
      "HandlerType": "BrowserIE", 

Instead of this:
        "handlerType": 0,

(for example - that's how I build timelines and it's worked for me)

**Comment by adavisec** [comment]
Using a string as the "HandlerType" definitely works for me when I drop the timeline.json file on the client. This is how I was doing it initially because I was leveraging the provided sample timelines. However, anytime I would try to send those through the API I would get a 500 response code.

When I looked at the timeline schema examples on swagger it showed the value as an interger. I referenced the "database data definitions" on the wiki and found that BrowserIE = 0. When I changed it to "handlerType": 0, the API would accept the input and the timeline.json file on the client would update.

**Comment by sei-dupdyke** [comment]
HandlerTypes are currently an enum, and maybe that is the source of confusion, because other places they are referred to in their string format, and here it is their corresponding int value that is used.

For reference [they are listed here in the code](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Domain/Messages/Timeline.cs#L69)

        BrowserIE = 0,
        BrowserFirefox = 1,
        BrowserChrome = 2,
        Command = 3,
        Notepad = 4,
        Outlook = 5,
        Word = 6,
        Excel = 7,
        PowerPoint = 8,
        NpcSystem = 9,
        Reboot = 10,
        Curl = 11,
        Clicks = 12,
        Watcher = 19,
        LightWord = 31,
        LightExcel = 32,
        LightPowerPoint = 33,
        Bash = 40,
        Print = 45

I'm going to re-open this issue and look to make them easier to use and match the conventions used elsewhere in a future update.

Thanks for pointing this out (and for your patience)!

**Comment by adavisec** [comment]
Thank you both for the help.

Mainly I am curious if there is something I can do to my input so that the actual commandArg string populates in the database rather than the valueKind? Am I formatting it wrong?

I'm poking around through the links that were posted and trying to look through the code, but I admit that .NET is not my strong suit haha.

**Comment by sei-dupdyke** [comment]
Sorry, I misunderstood. When I use the int values for handerType, it does save in the database properly and gets distributed when that agent checks in.

1. What are you seeing in the db? Run this from the command line on your docker server:
```
$ docker exec -it ghosts-postgres /bin/sh
# psql -U ghosts
ghosts=# select * from machineupdates;
```

Do you see your records here?

2. What are you seeing in logs for the api server right after you post to the api?
```
$ docker logs ghosts-api
```

Do you see any insert errors (or otherwise) here?

Thanks. Sorry for hassle.

**Comment by adavisec** [comment]
1. Yes I see the records in the database, but the commandArgs are being logged there as ValueKind:3 as well
```
 53 | 20ba0a08-01c9-4358-a99f-bac850281741 |    0 | 2020-06-16 18:00:00     | 2020-06-18 14:43:52.484048 |     -9 | {"Status":"Run","TimeLineHandlers":[{"HandlerType":"BrowserI
E","Initial":"about:blank","UtcTimeOn":"00:00:00","UtcTimeOff":"00:00:00","HandlerArgs":{},"Loop":true,"TimeLineEvents":[{"TrackableId":null,"Command":"random","CommandArgs":[{
"ValueKind":3},{"ValueKind":3},{"ValueKind":3},{"ValueKind":3},{"ValueKind":3},{"ValueKind":3},{"ValueKind":3},{"ValueKind":3},{"ValueKind":3},{"ValueKind":3},{"ValueKind":3}],
"DelayAfter":90000,"DelayBefore":0}]},{"HandlerType":"PowerPoint","Initial":"","UtcTimeOn":"00:00:00","UtcTimeOff":"00:00:00","HandlerArgs":{},"Loop":true,"TimeLineEvents":[{"T
rackableId":null,"Command":"create","CommandArgs":[{"ValueKind":3}],"DelayAfter":900000,"DelayBefore":0}]}]}
```

2. Thanks for showing me this command! I had been using docker exec to get into the container and search for relevant logs without any luck.

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM0JIHU9LDA9", Request id "0HM0JIHU9LDA9:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ghosts.Api.Services.TimelineService.UpdateAsync(MachineUpdateViewModel machineUpdateViewModel, CancellationToken ct) in /Users/dustin/Projects/ghosts/Ghosts.Api/Services/TimelineService.cs:line 35
   at ghosts.api.Controllers.TimelineController.Timeline(MachineUpdateViewModel machineUpdate, CancellationToken ct) in /Users/dustin/Projects/ghosts/Ghosts.Api/Controllers/TimelineController.cs:line 32
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

No hassel at all I definitely appreciate the help!

**Comment by sei-dupdyke** [comment]
Can you post what version of api docker container you are using please?

**Comment by adavisec** [comment]
This is what I get from docker image inspect. I stood them up on Tuesday with docker-compose.
"GHOSTS_VERSION=3.0.0.0",
"GHOSTS_API_VERSION=v2"

Here is what the browser shows:
localhost:5000/api/home:
version	"3.0.0.0"

**Comment by sei-dupdyke** [comment]
Well, this bug slipped through testing 😬  

I just posted a new container that will fix the error:

docker pull dustinupdyke/ghosts:v3.1.1.0

The problem was in serializing the args, they were previously objects. I moved the code to treat them as strings, which is all we have ever used there anyway.

Sorry for the bug. It should be fixed for good from here forward. LMK if you see anything wrong with the new container.

Thanks again.

**Comment by adavisec** [comment]
Wow that was quick, worked like a charm, thanks!

**Comment by sei-dupdyke** [comment]
I'm leaving this open as a reminder to revisit the docs for the API in the next update.

**Comment by sei-dupdyke** [comment]
For v4 (just released), I updated all the swagger documentation for the API, and moved it to the root of the C2, so hitting http://ghosts-c2/ puts you right into the swagger ui details. Hope this helps!
