### ISSUE TITLE
Installing API server

### ISSUE THREAD

**Issue by cajohntd** [cmu-sei/GHOSTS#29]
I am guessing this is a user error since I am new to Docker and Git.

I am trying to install GHOSTS for a Cyber Security Lab and I am having issues getting it installed from Docker.  I have a Debian 10 server setup to run the API server and I have installed Docker.  I have downloaded the code and when I run 
docker build . -t ghosts/api --no-cache -f dockerfile.api
This is returned:
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /ghosts/GHOSTS-master/Ghosts.Api/dockerfile.api: no such file or directory

When I change to 
docker build . -t ghosts/api --no-cache -f dockerfile
This is what I get:
Step 1/8 : FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine
 ---> 0e59b34ad3cb
Step 2/8 : COPY bin/publish/. /app/
COPY failed: stat /var/lib/docker/tmp/docker-builder375122196/bin/publish: no such file or directory

I would appreciate any help you can give me.

**Comment by sei-dupdyke** [comment]
Hi - 

If you also install docker-compose you should be able to just run `docker-compose up -d` and the entire stack will be built and configured within docker.

The command you are running is to actually build the container for distribution, which I don't think is what you are trying to do (apologies if I'm mistaken).

**Comment by cajohntd** [comment]
You were exactly right.  I got docker-compose installed and the api built and started seamlessly.

Question about the client; Do I have to build the csproj to get ghosts.exe and the other commands?

**Comment by sei-dupdyke** [comment]
Awesome!

You can download pre-built binaries via the instructions here: https://github.com/cmu-sei/GHOSTS/wiki/Installation-from-distribution-binaries

**Comment by cajohntd** [comment]
Thanks!  Client is working great.

Since I installed from the container, is the system running Grafana?

**Comment by sei-dupdyke** [comment]
Yes, it's just another container in the docker-compose stack that you started. It runs on that server's port 3000, and you can hit it in the browser at http://<ip or host>:3000

You can then load the specific GHOSTS dashboards by following the instructions posted above!

**Comment by playswithfir3** [comment]
So I've tried a couple times, and the API looks like it comes up fine with this but it appears that grafana isn't.

```
localadmin@ghosts-api:~/GHOSTS$ sudo docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                          PORTS                    NAMES
2030f36136e1        grafana/grafana       "/run.sh"                3 minutes ago       Restarting (1) 21 seconds ago                            ghosts-grafana
b4e1523f7b7e        dustinupdyke/ghosts   "dotnet ghosts.api.d…"   3 minutes ago       Up 3 minutes                    0.0.0.0:5000->5000/tcp   ghosts-api
df9875e285fb        postgres              "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes (healthy)          0.0.0.0:5432->5432/tcp   ghosts-postgres

```
It isn't listening on 3000, and appears to be in a reboot loop.

```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      3162/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1898/sshd
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      16142/sshd: localad
tcp        0    128 192.168.1.231:22        192.168.1.197:58295     ESTABLISHED 16014/sshd: localad
tcp6       0      0 :::22                   :::*                    LISTEN      1898/sshd
tcp6       0      0 :::5432                 :::*                    LISTEN      21329/docker-proxy
tcp6       0      0 ::1:6010                :::*                    LISTEN      16142/sshd: localad
tcp6       0      0 :::5000                 :::*                    LISTEN      21506/docker-proxy
```

**Comment by sei-dupdyke** [comment]
Do a `docker ps` and see if the docker interface gives you any more detail please.

One thing you might also look at is that docker has rights on your local volume. So docker maps an internal directory for the grafana config to a directory on your local machine (so that if the container goes away, your configuration remains for a new container to pick up and use). Look in the docker-compose.yml file for the local mapping, and give 777 permissions to that directory and try restarting the grafana container.

**Comment by playswithfir3** [comment]
Awesome, that worked. Thanks for the quick response!

**Comment by jaumemiralles** [comment]
Hi, I'm trying to install GHOSTS for a Cyber Security Lab and I am having issues getting it running.
I've a VM with Ubuntu Server 20.04 and I've installed docker and docker compose.
I just run docker-compose up -d and the entire stack will be built and configured within docker, [here is an image](https://drive.google.com/file/d/1rLd804Ybl3bFYuLDfqCFYWVkUnD31Tc3/view?usp=sharing)

I've run an nmap on localhost in the server and the result does'nt show the port 5000. [here is an image](https://drive.google.com/file/d/1CfHBB27qPqlkuwMFZWVLBmG1ht3cqadA/view?usp=sharing)


It seems than all is up and running,but I cannot connect to the api http://ip:5000/api/home/ I get a connection refused.
I think is because the port 5000 is not open in my server, but I don't understand why...

Can you help me?

**Comment by sei-dupdyke** [comment]
Hi, thanks for checking out the project.

Per your docker ps results, look at the ports for the API: 0.0.0.0:52388 is mapped to the container's port 5000. So in your browser, hit http://localhost:52388/api/home and you should be good to go.

IIRC, you have to specify all ports in nmap for it to go beyond the "most common" ports it typically scans, something like `nmap -p- 0.0.0.0`...

HTH

**Comment by jaumemiralles** [comment]
Ups!!!
My apologies! You're right! I think that yesterday not was my best day, sorry...

Thnkx!
