### ISSUE TITLE
API Examples

### ISSUE THREAD

**Issue by playswithfir3** [cmu-sei/GHOSTS#31]
Would you have any example API calls that could be included?

Can I tell a machine to open a specific email? Download a file from a website?

**Comment by sei-dupdyke** [comment]
Good question!

So, of course there are lots of different ways to do things within GHOSTS. Let me try to provide some context about what the API can do, and what it does under the covers.

For getting specific information about your clients, what they are doing and the like, beyond what the Grafana reports provide — unless you're doing raw sql queries in the database, the API is the best place to do this. Getting a list of machines (and their IDs, which we'd need in order to change what those machines are doing) is pretty easy via the API.

The client machines are operating off timelines. The default timeline in ./config/timeline.json basically tells the machine what to do night and day without any intervention. So you might set it up to do emails, office docs and browsing on some random schedule, and your clients will be out there doing what office people do throughout the day.

There is another mechanism that enables "right now" things. So a client will keep doing its default timeline activities, but spin a new thread up to do the thing you tell it to do right now. This is done via a folder in ./instance/timeline/in - any timeline file dropped in here will be executed immediately upon receipt and moved to the out folder. You could do this on the box, via some other management utility (such as Ansible or the like), it just has to be able to write/move files around on that client box.

The API can do this as well, what basically happens is that you post a new timeline as the default or as right now, and the next time that machine checks in, it pulls that file down and writes it locally. So via the API you can update your machines on the fly.

For your specific questions, opening an email is still kind of difficult (which is probably a separate thread), we typically do a drive by download instead, but you can definitely do this by setting up a handler to download a specific payload, then running an unzip and finally an execute something.

Here is an example that downloads and unzips a font from a website:

```
{
    "TimeLineHandlers": [
        {
            "HandlerType": "BrowserChrome",
            "Initial": "about:blank",
            "UtcTimeOn": "00:00:00",
            "UtcTimeOff": "24:00:00",
            "Loop": false,
            "TimeLineEvents": [
                {
                    "Command": "browse",
                    "CommandArgs": [ "https://dl.dafont.com/dl/?f=italian_breakfast" ],
                    "DelayAfter": 0,
                    "DelayBefore": 0
                },
                {
                    "Command": "download",
                    "CommandArgs": [ "//a[contains(@class, 'dl')]" ],
                    "TrackableId": "<guid id from trackables table/>",
                    "DelayAfter": 0,
                    "DelayBefore": 0
                }
            ]
        },
        {
            "HandlerType": "Command",
            "Initial": "",
            "UtcTimeOn": "00:00:00",
            "UtcTimeOff": "24:00:00",
            "Loop": false,
            "TimeLineEvents": [
                {
                    "Command": "cd %homedrive%%homepath%\\Downloads",
                    "CommandArgs": [
                        "powershell expand-archive -Path italian_breakfast.zip -destinationpath x",
                        "cd x",
                        "dir"
                    ],
                    "TrackableId": "<guid id from trackables table/>",
                    "DelayAfter": 10,
                    "DelayBefore": 10000
                }
            ]
        }
    ]
}
```

Another concept here is the use of tracking numbers (which is just a guid) to be able to quickly track that something completed. We can then look for these in the activity history to ensure that activities we were waiting for completed.

**Comment by briangreunke** [comment]
I am a little unclear on how to POST a new/updated timeline. The comment in #22 mentioned the "timeline" route but I cannot seem to find that. Could you elaborate on how you can update a timeline?

**Comment by sei-dupdyke** [comment]
Sure!

You can follow along locally, by opening http://localhost:5000/swagger/index.html (or whatever your local install url is).

We can get the machines currently in your system via: GET /api/Machines, click that blue button to expand this section. Now click "try it out" and finally "Execute". Below you'll see details about the command we just ran, and its results, which look something like:

```
[
  {
    "id": "1288b6e0-5075-4280-96a3-2797aa15e22f",
    "name": "test1",
    "fqdn": "test1.fqdn.variable.tld",
    "domain": "domain",
    "host": "test1",
    "resolvedHost": "test1.resolved.host",
    "hostIp": "0.0.0.0",
    "ipAddress": "192.168.0.11",
    "currentUsername": "testuser1",
    "clientVersion": "2.4.7.0",
    "status": "Active",
    "createdUtc": "2020-04-24T13:40:29.637599",
    "statusMessage": "Active & Down",
    "statusUp": "Down",
    "lastReportedUtc": "2020-04-24T14:06:22.182392"
    ...
```

Note the CURL command, we'll come back to that in a moment. For now, copy the Id of the first machine (here 1288b6e0-5075-4280-96a3-2797aa15e22f).

Now look under the Timeline section, there are endpoints listed for a machine or a group of machines, let's try the former. The value we're sending is basically a wrapped timeline object:

```
{
  "machineId": "1288b6e0-5075-4280-96a3-2797aa15e22f",
  "type": "Timeline",
  "activeUtc": "2020-04-24T15:16:02.393Z",
  "status": "Active",
  "update": {
    -- timeline json object here --
  }
}
```
This sends the timeline to the machine specified. Again, note the CURL line once you try this out.

If you want to script all of this, an easy way to get started is to copy those curl commands. Using [postman](https://www.postman.com/downloads/), you can import raw text commands, and then export in your favorite programming language (python, node, js, etc).

**Comment by sei-dupdyke** [comment]
I just realized the docker hub version of the api needed updated. Please be sure to pull the latest image.

**Comment by briangreunke** [comment]
Thanks for the quick response! The update now has the timeline routes. I will test this out.
