### ISSUE TITLE
Server API install guide and dockerfile out of date

### ISSUE THREAD

**Issue by exedar37** [cmu-sei/GHOSTS#32]
I'm trying to install the server API with the docker instructions (https://github.com/cmu-sei/GHOSTS/wiki/Installing-the-Server-API) but the path for bin/publish seems to be gone or out of date.  Additionally the dockerfile appears to need updating since bin/publish from step 2 doesn't exist.

**Comment by sei-dupdyke** [comment]
Hello - 

1. Do you get this result from `docker run...` or `docker-compose up...`
2. What command did you initially run? 
3. Did you get a specific error message? 

Thanks!

**Comment by exedar37** [comment]
Thanks for the quick reply!  This is a really cool project.

1) I got it from a modified version of the `docker build . -t ghosts/api --no-cache -f dockerfile-api` command in the guide under the Docker-Based Setup heading.
1a) After this post I switched to using `docker-compose up -d` which seems to do the trick.  Looks like the docker build step isn't necessary?  This might be moot but if just running the docker-compose step does the trick, it might be a good idea to remove the old guidance from the instructions.

2) What I did was cd to the Ghosts.Api directory, and ran `docker build . -t ghosts/api --no-cache -f dockerfile`

3) The error message was related to the `COPY` step in the dockerfile: https://github.com/cmu-sei/GHOSTS/blob/master/Ghosts.Api/dockerfile#L5 since that directory structure doesn't seem to exist anymore.

**Comment by exedar37** [comment]
Shoot I forgot to post the error message:
`
Step 2/8 : COPY bin/publish/. /app/
COPY failed: stat /var/lib/docker/tmp/docker-builder514221183/bin/publish: no such file or directory
`

**Comment by sei-dupdyke** [comment]
Awesome, thanks for this info. I will recreate it here and update the docs. Honestly, I'm so used to using docker-compose, I could have missed a change, sorry about that confusion.

I'm glad that you have it up and running though - lmk if you have any other issues or questions. Thanks again.

**Comment by sei-dupdyke** [comment]
Ah, I see the problem now. The instructions page you linked isn't terribly clear, but that path is essentially for building code and container from scratch. If you want to just deploy pre-built containers, I put a note in there to use this page: https://github.com/cmu-sei/GHOSTS/wiki/Installation-from-distribution-binaries in order to try and make this more clear. I think most people just want to deploy and configure, so I'll go through pages and call that out where applicable.

Sorry for the confusion and thanks for letting me know about it.
