### ISSUE TITLE
Windows Client Error on Launch

### ISSUE THREAD

**Issue by Ph3n0mZ** [cmu-sei/GHOSTS#369]
I receive the following error when attempting to launch the latest client on my range's Windows 10 virtual machine. 
![GhostClientErrorMsg](https://github.com/cmu-sei/GHOSTS/assets/49131577/59e4c3f4-6a33-4ab1-b6b3-91900a04d57d)

Is the client looking for a file location that doesn't exist?

**Comment by sei-dupdyke** [comment]
The client can't fine its configuration - did you move the ./config folder?

**Comment by Ph3n0mZ** [comment]
I don't believe I have.. 
I downloaded the the client, extracted the zipped file and then attempted to run the application with no changes.
On another windows system, I did try and update the api server information but received the same error, so I then tried to run with no changes to the config file on a separate system.
Am I installing it incorrectly? I don't have a Projects folder on the root of the C: drive as it shows in the error.

**Comment by sei-dupdyke** [comment]
Does the user that you're using to execute ghosts.exe have permissions to the folders within ./ghosts?

**Comment by adiclapa** [comment]
Any updates on this? I am facing the same issue with the windows client.

**Comment by sei-dupdyke** [comment]
The Ghosts binary does not have rights to the config folder (see the SECURITY_ATTRIBUTES flag in the above screen shot) - can you check permissions on everything inside the top level ghosts folder please?

**Comment by adiclapa** [comment]
I don't think that's the issue. The path in the screenshot (and in my error too) is `C:\Downloads\ghosts-client-x64-v8.0.0\ghosts-client-x64-v8.0.0\ghosts.exe\config\application.json` which contains the name of the executable `ghosts.exe`. This might be caused by this line of code in ` ApplicationDetails.cs:104`:
```
 public static string InstallPath => InstalledPath + $"{System.IO.Path.DirectorySeparatorChar}config{System.IO.Path.DirectorySeparatorChar}";
```
Where InstalledPath "Returns installed exe path, for commands like c:\exercise\ghosts\ghosts.exe to work properly" as mentioned in the summary (ApplicationDetails.cs:50). This results in the config path containing the name of the exe.

Correct me if I'm wrong but I don't think the directory permissions are the issue.

**Comment by sei-dupdyke** [comment]
After thousands of installs, I have never seen this issue, but I see it now — the potential is:

"ghosts.exe" is removed from that string with Path.GetDirectoryName()... Unless .CodeBase is not working on your system then it falls back to .Location which is missing the Path call. 

PR #388 fixes this. v8.1.1 client is out there for download. Sorry for the inconvenience.

**Comment by adiclapa** [comment]
Thank you for your time. Keep on with the good work!
