### ISSUE TITLE
Use of CommandArgs

### ISSUE THREAD

**Issue by RANDW0LF** [cmu-sei/GHOSTS#46]
I am trying to use the click command after the Browser command.
Is there any documentation on what CommandArgs can be used to click on links within a website.
I note "click: Once you have browsed to a page, use this to click a link by it's name (supplied as CommandArgs[0])."
What is considered to be "by its name"?

**Comment by sei-dupdyke** [comment]
Hi, thanks for looking at this. Docs are probably weak on this particular function, sorry!

Walking through the sample timeline [here](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Sample%20Timelines/BrowserChrome.json) — the three steps are:

1. go to google.com

2. find the page element named "q" and enter "test search string". If you look at the google homepage in your browser, and right click on the text input for searching and choose "inspect", you should see something like:

```
<input name="q" type="text" aria-autocomplete="both" aria-haspopup="false" autocapitalize="off" autocomplete="off" autocorrect="off" autofocus="" role="combobox" spellcheck="false" title="Search" value="" aria-label="Search">
```

Note the element name attribute "q". The interface with the browser allows us to interact with page elements by this.

3. find the page element named "btnK" and click it. Again, if you right click on the "google search" button and inspect, you should see something like:

```
<input value="Google Search" aria-label="Google Search" name="btnK" type="submit">
```

If I'm honest, this section could probably use an upgrade, but one of the things we've struggled with is (1) being able to do so without requiring a lot of configuration on the user's part in order to have the browser do very specific actions and (2) not having that configuration wind up being very brittle in terms of if anything changes on those web sites, aka — a button changes — and the configuration no longer works. There are [tools by Selenium](https://www.selenium.dev/selenium-ide/) that automate browser activity like this for testing purposes, and they have probably matured quite a bit since we last looked at them, so that might be an option going forward.

I'm also curious how many people are using this functionality so that I could prioritize that work accordingly.

**Comment by RANDW0LF** [comment]
Sorry for the late reply.

Thankyou for the information, I also found an earlier post:
https://github.com/cmu-sei/GHOSTS/issues/18. This actually helped with what
I was trying to achieve in addition to your response.
