### ISSUE TITLE
Random Reboot

### ISSUE THREAD

**Issue by nunoguerreiro** [cmu-sei/GHOSTS#60]
Is there is any way to simulate a reboot randomly or in specific hours ?

**Comment by sei-dupdyke** [comment]
Yes, check out the [timeline config here](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Sample%20Timelines/Reboot.json) for rebooting a machine.

**Comment by nunoguerreiro** [comment]
> Yes, check out the [timeline config here](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Sample%20Timelines/Reboot.json) for rebooting a machine.

I mean - to have an option in the timeline reboot handler to make a random reboot during the interval specified in the handler.

**Comment by sei-dupdyke** [comment]
Oh! Sorry, I misunderstood.

Change the values for UtcTimeOn and UtcTimeOff to the time you want to reboot, and then set Loop to false in order to have it occur only once in that timeframe:

```json
{
    "TimeLineHandlers": [
        {
            "HandlerType": "Reboot",
            "Initial": "",
            "UtcTimeOn": "03:00:00",
            "UtcTimeOff": "04:00:00",
            "Loop": false,
            "TimeLineEvents": [
                {
                    "Command": "",
                    "CommandArgs": [ ],
                    "DelayAfter": 0,
                    "DelayBefore": 0
                }
            ]
        }
    ]
}
```

Another option is to script a call to the API with similar:

curl -X POST "http://localhost:5000/timeline" -H "accept: text/plain" -H "Content-Type: application/json" -d "{\"machineId\":\"3fa85f64-5717-4562-b3fc-2c963f66afa6\",\"type\":0,\"activeUtc\":\"2021-03-17T11:56:08.520Z\",\"status\":0,\"update\":{\"status\":0,\"timeLineHandlers\":[{\"HandlerType\":\"Reboot\",\"Initial\":\"\",\"UtcTimeOn\":\"03:00:00\",\"UtcTimeOff\":\"04:00:00\",\"Loop\":false,\"TimeLineEvents\":[{\"Command\":\"\",\"CommandArgs\":[],\"DelayAfter\":3600000,\"DelayBefore\":0}]}]}}"

**Comment by nunoguerreiro** [comment]
If I understood well, the 
"UtcTimeOn": "03:00:00", and "UtcTimeOff": "04:00:00" will define an interval and then handler will define a random hour during this interval right ?

**Comment by sei-dupdyke** [comment]
Yes, that is correct.
