### ISSUE TITLE
ghosts.api.dll missing

### ISSUE THREAD

**Issue by brandonrasaka** [cmu-sei/GHOSTS#80]
Hello,
I am trying to set up GHOSTS "from scratch" without Docker. The instructions in for [setting the API](https://github.com/cmu-sei/GHOSTS/wiki/Installing-the-Server-API#api) say to run this command:
`$ dotnet ghosts.api.dll`
However, I can't find that DLL file is not found anywhere in the repo. Am I missing something?

**Comment by sei-dupdyke** [comment]
Hi Brandon - 

If you downloaded the repo, that's just source files, you'll still need to run a build.

But your issue did make me realize I don't have the built binaries available anywhere if you want to skip that step!

So [I've made it available here](https://cmu.box.com/s/gz62rltw8ajkhomt3c2kvbtpw56yikd1) and I'll update the "install from binaries" page in the wiki. For this, you'll need v6 of the dotnet framework (we'll stay on this version for a while because it is slated for extended support). You can [get that here](https://dotnet.microsoft.com/download/dotnet/6.0) - note that you only need the runtime, not the sdk.

Hope this helps, and sorry for the confusion.
