### ISSUE TITLE
No email-content and email-reply csv files

### ISSUE THREAD

**Issue by danielgarner64** [cmu-sei/GHOSTS#9]
The following files are in the gitignore:
ghosts.tools.emailgenerator/config/email-content.csv
ghosts.tools.emailgenerator/config/email-content - Copy.csv
Ghosts.Client/config/email-reply.csv
Ghosts.Client/config/email-content.csv

The code requires these files to compile. 
I can add them in myself but obviously I don't know if there is any special format for these files.
Is it just a whole load of comma separated words to be inserted into emails or something else?
Can you please provide information about what should be in the files or a copy of the files you use.

**Comment by swilliams70** [comment]
Check out this:
https://github.com/cmu-sei/GHOSTS/wiki/Configuring-the-Windows-Client

There's a section in there that talks about the files and gives an example for one of them. For the replys, there's no example, but I'm guessing that it's just a rando text string per line that the NPC selects from to compose the emails.

Unfortunately, I can't validate that for you, since I'm badly stuck on trying to get the API to work.

**Comment by sei-dupdyke** [comment]
Sorry for delay!

Email content is in the format:
"ID"|"SUBJECT"|"BODY"

Email reply is simply (because subject stays same): 
Body
